name: "deploy to server"

on:
  push:
    branches: ["main"]
  
jobs: 

  first_job:
    runs-on: ubuntu-latest
    env:
      name: "hola mundo"
    
    
    steps:
          
      - name: hola munndo
        run: echo "hola mundo $name"

  second_job:
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: first_job
    runs-on: ubuntu-latest
    
    steps:
    
      - name: hola munndo 2
        run: echo "hola mundo 2"
