name: "deploy to server"

on:
  push:
    branches: ["main"]
  
jobs: 

  first_job:
    runs-on: ubuntu-latest


    outputs:
      salida: ${{ steps.step1.outputs.variable }}
    
    steps:
          
      - name: hola munndo
        id: step1
        run: echo "variable= holaaa mundo" >>  $GITHUB_OUTPUT
        
      - name: print variablee
        run: echo "${{ steps.step1.outputs.variable }}"
    
  second_job:
    runs-on: ubuntu-latest
    needs: first_job

    env:
      salida: ${{ needs.first_job.outputs.salida }}
    
    steps:
      - name: print variable from first job
        run: echo "${{ needs.first_job.outputs.salida }}"
      