name: "deploy to server"

on:
  push:
    branches: ["main"]
  
jobs: 

  first_job:
    runs-on: ubuntu-latest
    env:
      name: "holiii"
    
    
    steps:
          
      - name: hola munndo
        id: step1
        run: echo "variable= holaaa mundo" >>  $GITHUB_OUTPUT
        
      - name: print variablee
        run: echo "${{ steps.step1.outputs.variable }}"
      
    